export const ADD_MED = 'ADD_MED';
export const ADD_MED_FULFILLED = 'ADD_MED_FULFILLED';
export const DELETE_MED = 'DELETE_MED';
export const DELETE_MED_FULFILLED = 'DELETE_MED_FULFILLED';
export const LIST_MED = 'LIST_MED';
export const LIST_MED_FULFILLED = 'LIST_MED_FULFILLED';

export const LIST_MED_HISTORY = 'LIST_MED_HISTORY';
export const LIST_MED_HISTORY_FULLFILLED = 'LIST_MED_HISTORY_FULFILLED';
