export const ADD_MED = "ADD_MED"
export const ADD_MED_FULFILLED = "ADD_MED_FULFILLED"
export const LIST_MED_HISTORY = "LIST_MED_HISTORY"
export const LIST_MED_HISTORY_FULLFILLED = "LIST_MED_HISTORY_FULFILLED"