export const ADD_TIME = 'ADD_TIME';
export const ADD_TIME_FULFILLED = 'ADD_TIME_FULFILLED';
export const CHECK_WETHER_REPORTED = 'CHECK_WETHER_REPORTED';
export const CHECK_WETHER_REPORTED_FULFILLED = 'CHECK_WETHER_REPORTED_FULFILLED';
export const CLEAR_REPORTING_DATA = 'CLEAR_REPORTING_DATA';
